---
- name: Ubuntu Workstation Configuration
  hosts: localhost
  connection: local
  become: true
  vars:
    hostname_prefix: "propetro-intelie-"
    hostname_suffix: ""

  tasks:
    - name: Request server identification number *ATTENTION*
      ansible.builtin.pause:
        prompt: "Enter the server identification number: It must start with the number 64 and cannot be repeated. (e.g.: 64, 65, 107):"
      register: hostname_suffix_answer

    - name: Generate new hostname
      set_fact:
        new_hostname: "{{ hostname_prefix }}{{ hostname_suffix_answer.user_input }}"

    - name: Change hostname to {{ new_hostname }}
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: Install ntpdate package
      apt:
        name: ntpdate
        state: present

    - name: Synchronize time with pool.ntp.org
      shell: ntpdate -v pool.ntp.org

    - name: Update package list cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install QEMU and KVM packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - iptables-persistent
        - qemu
        - qemu-kvm
        - bridge-utils
        - libvirt-daemon-system
        - libvirt-clients
        - virt-manager

    - name: Enable and start QEMU services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - qemu-kvm
        - libvirtd

    - name: Add FORWARD rule to allow traffic on port 8081
        iptables:
          chain: FORWARD
          insert: I
          protocol: tcp
          port: 8081
          jump: ACCEPT

    - name: Add DNAT rule to redirect port 8081 to 192.168.122.100:8081
        iptables:
          table: nat
          chain: PREROUTING
          protocol: tcp
          port: 8081
          jump: DNAT
          to_destination: 192.168.122.100:8081
